### ISSUE TITLE
Timer running too fast

### ISSUE THREAD

**Issue by beojan** [Zren/plasma-applet-eventcalendar#129]
The timer is running too fast, showing a second elapsed after approximately 0.5 s.

**Comment by Zren** [comment]
I've no idea how that could happen. There's only 1 Timer instance and it only triggers every 1000ms.

https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/TimerView.qml#L263

If anything, I'd expect the overhead of the timer would make it take longer (eg: 2h00m30s instead of a clean 2h).

**Comment by sahsanu** [comment]
Same issue here, timer for 30 seconds ends in 15 seconds, 1 minute in 30 seconds and so on.

Event Calendar v66
KDE Neon 5.18.5
QT 5.14.2

**Comment by Zren** [comment]
Does it happen all the time? Even after a reboot?

**Comment by sahsanu** [comment]
No, it doesn't happen all the time. Sometimes works fine and other times it is too fast (0.5 seconds instead of 1 second). I can reboot and it works fine after reboot or I reboot and it doesn't work fine, it is a bit erratic in my case. Really weird.

**Comment by beojan** [comment]
That's exactly what I see too.

**Comment by Zren** [comment]
The only thing I can think of besides a QML bug is:

* the eventcalendar popup getting unloaded when not used
* since the `Timer {}` is in the popup, it might not be destroyed properly... for god knows what reason.
* when you open the popup, it creates a second `Timer {}` instance.
* Both Timers run `timerView.timerSeconds -= 1`.

If you pause the timer, does it still count down? Does it still go at double speed when to unpause it?

**Comment by beojan** [comment]
It goes at double speed from the moment I start the timer, so the popup is never closed.
Of course when I go to test it, it works, making it pretty hard to debug.

I should add, I have eventcalendar in a Latte Dock. @sahsanu, what about you?

**Comment by sahsanu** [comment]
> If you pause the timer, does it still count down? 

No, it pauses correctly.

> Does it still go at double speed when you unpause it?

Yes, if it started double speed no matters whether I pause/unpause, it continues at double speed.

> I should add, I have eventcalendar in a Latte Dock. @sahsanu, what about you?

I've latte-dock installed but Event Calendar is on a normal panel, not a latte-dock panel.

**Comment by JuBan1** [comment]
It happens to me too. Here's a video of it: https://streamable.com/49bpuw

Manjaro Linux, Plasma 5.18 (and several versions prior))

What's even weirder: *sometimes* it works fine. Occasionally I'd use the timer and it's too fast, then I'd use it a few hours later (without restarting anything) and it would work fine.

I'm thinking it might be related to the display refresh rate (or rather, VSync). I have a 144Hz monitor, which is ~2.5x more then 60Hz, and the calendar timer runs ~2.5x faster than it should. In addition there have been issues like that in the past. [1](https://bugreports.qt.io/browse/QTBUG-42699) [2](https://bugreports.qt.io/browse/QTBUG-59300)

But it's not as easy as just going back to 60Hz. That doesn't fix it- at least not immediately. So I might be on the wrong track. But even just fiddling around a bit right now as I collected information, somehow, the calendar timer once again started working properly.

**Comment by Zren** [comment]
So apparently this was a bug in Qt 5.4.x. Someone also mentioned on StackOverflow that it's tied to the refresh rate. I guess I will go with `(timeStarted + duration) - timeNow = timeLeft` rather than using a QML Timer tick every second...

* https://stackoverflow.com/questions/22752201/qml-timer-not-triggered-in-the-right-interval
* https://bugreports.qt.io/browse/QTBUG-41198
* https://bugreports.qt.io/browse/QTBUG-42699

... Or I could use the time datasource... like the clock uses... I've been an idiot for not using all this time. I got caught up in trying to figure out what was wrong with QML Timers.

* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/TimeModel.qml#L29

**Comment by JuBan1** [comment]
Good to hear. I can help if you need someone to test a patch. I can consistently reproduce the behavior, unfortunately.

**Comment by Zren** [comment]
It should work now. It still uses QML Timer, but depends will now use this logic.

```python3
def start():
    finished = now + duration
def tick():
     timeLeft = finished - now
```

I still need to figure out a "timestamp that isn't affected by timezones" like seconds the plasmashell process has been running. Right now I think Daylight Savings Time or physically moving over timezones might break my timer logic.

**Comment by JuBan1** [comment]
I've tested the changes and here are two observations:

* I can't say for certain but it seems to me that the interval between each second isn't constant. Just staring at the timer, a second sometimes seems to elapse faster or slower. But that's a minor issue.

* The time still isn't entirely accurate. I timed 60 real seconds, during that time the calendar timer elapsed by 70 seconds.

**Comment by JuBan1** [comment]
(Ignore my last comment if you saw it. I did a ./reinstall but it work; so my previous comment was still about the buggy code.)

I tested it and it does work accurately now.

**Comment by Zren** [comment]
There's also a KDE Bug report that some of you might be able to reproduce.

* https://bugs.kde.org/show_bug.cgi?id=419421 QML timers go too fast with multi-threaded render loop when using mixed 240hz + 60hz refresh rate screens on X11
* https://bugs.kde.org/show_bug.cgi?id=419421#c31 An interesting test.

**Comment by EverardNisse** [comment]
Can reproduce the KDE bug with 144+75 Hz displays / 144+60 Hz. They're on the right track, the workaround mentioned there seems to also work.
